In [1]:
import random
import glob
import os
import openpyxl
import pandas as pd
import numpy as np
from fuzzywuzzy import fuzz
import sqlite3

In [ ]:
import shutil

# Set the source and destination directories
source = '/Users/jaredperez/Downloads/Client Folders'
dst = '/Users/jaredperez/' #Don't Need to Run again

# Move the folder
shutil.move(source, dst)

In [2]:
def grab_workout(client):
    # Find all of my client files in the directory
    selection=f'/Users/jaredperez/Client Folders/{client}.xlsx'
    workbook = openpyxl.load_workbook(selection)
    sheet=random.choice(workbook.sheetnames)
    df=pd.read_excel(selection, sheet_name=sheet, header=3)
    df=df.dropna(how='all')
    df=df.fillna(0)
    start= df.sample(1).index[0]
    workout=df.iloc[start:start+20]
    return workout

In [13]:
grab_workout('Daniel').iloc[:,:2]

4/24-4/30 (10 reps)             Prescription
46                  Pushups                     3x10
47             Hollow Holds                 3x30 sec
48             Plate Squats                  3x10 ES
49          Plank to Pushup                 3x30 sec
50             3:45 Circuit                       1x
51                  Burpees                     3x10
52         Roll Out/Stretch                        0
57  Emphasis: Core Strength                        0
60       5/15-5/21 (8 reps)             Prescription
61                        0  %=of perceieved maximum
62         Workout 1-FB (L)    95-100%=0-1 reps left
63                Foam Roll                       1x
64              Up/Down Dog                       2x
65        Mountain Climbers              4x30 sec ES
66    Adduction Side Planks                  3x10 ES
67                  Pushups                     3x10
68             Hollow Holds                 3x30 sec
69             Plate Squats                  3x10 ES
70          Plank to Pushup                 3x30 sec
71             3:45 Circuit                       1x

In [1]:
intensity=['high', 'moderate', 'low']

In [ ]:
goal=['Hypertrophy', 'Strength', 'Endurance']

In [261]:
df=pd.read_excel(f'/Users/jaredperez/Client Folders/Yelena.xlsx', sheet_name='Jan 2022', header=3)
df=df.dropna(how='all')
df=df.fillna(0)

In [262]:
df

Unnamed: 0  %=of perceieved maximum  \
0                                       0  (suggested start point)   
1               Stairs (every other Step)                        0   
2                        Workout 1-Pushes                        0   
3                               Stairs x2                        0   
4             Sagital Banded Walks (Toes)                  3x1 Min   
..                                    ...                      ...   
231  Chest Press Machine (DB Bench Press)                     3x10   
232                              DB Curls                     3x10   
233                          DB Kickbacks                     3x10   
234                                     0                        0   
235                                     0                        0   

                 Unnamed: 2 Unnamed: 3 If timed exercise   Unnamed: 5  \
0            Weight Lifted=          0                  0         0.0   
1    Band Thickness (2,3,4)          0                  0         0.0   
2                         0          0                  0         0.0   
3                         0          0                  0         0.0   
4                         0          0                  0         0.0   
..                      ...        ...                ...         ...   
231                      20          3                 12         0.0   
232                       9          3                 12         0.0   
233                       9          3                 10         0.0   
234                       0          0                  0         0.0   
235                       0          0                  0         0.0   

    Unnamed: 6 Unnamed: 7 (VL/total Rep)  Unnamed: 9 Unnamed: 10 Unnamed: 11  
0            0          0              0         0.0           0           0  
1            0          0              0         0.0           0           0  
2            0          0              0         0.0           0           0  
3            0          0              0         0.0           0           0  
4            0          0              0         0.0           0           0  
..         ...        ...            ...         ...         ...         ...  
231        720         36             20         0.0           0           0  
232        324         36              9         0.0           0           0  
233        270         30              9         0.0           0           0  
234          0          0        #DIV/0!         0.0           0           0  
235      40842        438      93.246575         0.0           0           0  

[197 rows x 12 columns]

In [7]:
exercises=df.iloc[:,0]

In [10]:
exercises.unique() #Let's combine this with the exercises.unique from each sheet to get a comprehensive list

array([nan, 'Workout 1-UB ', 'Upward Downward Dog',
       'UB Warm Up (Cat Cow, Opposite Arm/Leg, Plank)',
       'Pushup Position Arm Raises', 'Pushups*', 'Bench Press*',
       'SA Renegade Row**', 'Snow Angels**', 'TRX High Row',
       'SIde Plank w/Press', 'Strict Elbow Curls', 'Stretches',
       'Workout 2-FB ', 'Up/Down Dog',
       'LB Warm Up (Bridges, Bridge Marches, Dead Bugs)', 'Lateral Walks',
       'Pause Plate Squats w/Band ', 'Squat Thruster',
       'SA OH Reverse Lunge', 'Side Plank w/high knee', 'TRX Low Rows',
       'Full Curls', 'UB Strength', '1/8-1/14 (MH)', '1/15-1/21 (H)',
       '1/22-1/28 (L)'], dtype=object)

In [5]:
xlsx=pd.ExcelFile(f'/Users/jaredperez/Client Folders/Ilya.xlsx')

In [6]:
sheets=xlsx.sheet_names

In [7]:
sets=[]
exercises=[]
reps=[]
for sheet in sheets:
    df=pd.read_excel(xlsx, sheet_name=sheet, header=3)
    df=df.dropna(how='all')
    df=df.fillna(0)
    sets.append(df.iloc[:,3].unique)
    exercises.append(df.iloc[:,0].unique) #Because of misformatted data, make sure to pop 1st entry
    reps.append(df.iloc[:,4].unique)

In [53]:
arr=sets[0]() #Now I want to get all the uniques in each array and put them in a single scalar only array

In [168]:
for idx,i in enumerate(sets):
    sets[idx]=sets[idx]()#Convert the objects to arrays

In [169]:
sets

[array(['3x15,12,8 @25', '3x5,6, 8 @5lbs', '3x10 @5lbs', '3x10,12,10', 0],
       dtype=object),
 array([0, 3, 'Sets'], dtype=object),
 array([0, 3, 'Sets'], dtype=object),
 array([0, 2, 4, 3, 'Sets', 5], dtype=object),
 array([0, 3, 4, 'Sets'], dtype=object),
 array([0, 3, 'Sets', 4], dtype=object),
 array([0, 3, 'Sets'], dtype=object),
 array([0, 3, 'Sets'], dtype=object),
 array([0, 4, 3, 'Sets'], dtype=object),
 array([0, 3, 'Sets'], dtype=object),
 array([0, 3, 'Sets'], dtype=object),
 array([0, 3, 'Sets'], dtype=object),
 array([0, 3, 'Sets'], dtype=object),
 array([0, 3, 'Sets', 4, 2, 1], dtype=object),
 array([0, 3, 'Sets', 4], dtype=object),
 array([0, 3, 4, 'Sets'], dtype=object),
 array([0, 3, 'Sets'], dtype=object),
 array([0., 1., 3.])]

In [170]:
sets.pop(0)

array(['3x15,12,8 @25', '3x5,6, 8 @5lbs', '3x10 @5lbs', '3x10,12,10', 0],
      dtype=object)

In [171]:
sets = [elem for sublist in sets for elem in sublist if isinstance(elem, (int, float))]

In [172]:
sets=np.asarray(sets)

In [173]:
sets=np.unique(sets)

In [174]:
sets

array([0., 1., 2., 3., 4., 5.])

In [175]:
for idx,i in enumerate(exercises):
    exercises[idx]=exercises[idx]()#Convert the objects to arrays

In [176]:
exercises=np.asarray(exercises)

/var/folders/wv/c3g7vgxd10n0mdl2_flcjj480000gn/T/ipykernel_67084/771042603.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  exercises=np.asarray(exercises)


In [177]:
exercises=[elem for sublist in exercises for elem in sublist if isinstance(elem, (str))]

In [178]:
exercises=np.asarray(exercises)

In [179]:
exercises=np.unique(exercises)

In [180]:
exercises=list(exercises)

In [181]:
exercises

['1/15-1/21 (H)',
 '1/22-1/28 (L)',
 '1/8-1/14 (MH)',
 '10/17-10/23 (MH)',
 '10/24-10/30 (H)',
 '10/3-10/9 (H)--Wrist pain',
 '10/3-10/9 (L)',
 '10/31-11/6 (L)',
 '11/27-12/2 (H)',
 '12/12-12/18 (H)',
 '12/19-12/25 (L)',
 '12/3-12/9 (L)',
 '12/4-12/10 (M)',
 '12/5-12/11 (MH)',
 '2/15-2/21 (H)',
 '2/22-2/28 (L)',
 '2/8-2/14 (MH)',
 '3/15-3/21 (H)',
 '3/22-3/28 (L)',
 '3/8-3/14 (MH)',
 '4/17-4/23 (Moderate Heavy-3x10 @Bench)',
 '5/1-5/7 (Heavy-3x12 @Bench)',
 '5/1-5/7 (Light-3x6 @Bench)',
 '5/22-5/28 (MH)',
 '5/29-6/4 (H)',
 '6/19-6/25',
 '6/20-6/26',
 '6/26-7/2 (H)',
 '6/27-7/3',
 '6/5-6/11 (L)',
 '7/18-7/24',
 '7/25-7/31 (traveling)',
 '7/3-7/9 (L)',
 '7/4-7/10 (deload)',
 '8/1-8/7 Traveling',
 '8/15-8/21 (M)',
 '8/22-8/28',
 '8/22-8/28 (M)',
 '8/29-9/4',
 '9/12-9/18 (MH)',
 '9/19-9/25 (MH)',
 '9/26-10/2 (H)',
 '9/5-9/11',
 'Alternating Reverse Lunge',
 'Banded Goblet Pause Squat',
 'Banded Walks',
 'Bench Press',
 'Bench Press*',
 'Bent Over Rows',
 "Bent Over T's",
 'Bicep Curls',
 '

In [182]:
original_list = exercises
char_to_remove = [str(i) for i in (range(10))] 

In [183]:
char_to_remove

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [184]:
f=filter(lambda x: not any(y in x for y in char_to_remove), exercises)

In [185]:
exercises=list(f)

In [186]:
exercises

['Alternating Reverse Lunge',
 'Banded Goblet Pause Squat',
 'Banded Walks',
 'Bench Press',
 'Bench Press*',
 'Bent Over Rows',
 "Bent Over T's",
 'Bicep Curls',
 'Bicycles',
 'Bilateral DB Bent Over Row',
 'Bilateral DB Row*',
 'Bodyweight (Traveling)',
 'Bodywieght Squats',
 'Burpees',
 'Curl to OH Press',
 'Curl to OH Press*',
 'Curls',
 'DB Alternating Forward Lunge',
 'DB Alternating Reverse Lunge',
 'DB Bench Press',
 'DB Bench Press*',
 'DB Curl to OH Press',
 'DB OH Press',
 'DB OH Press*',
 'DB Push Press',
 'DB Shoulder Shrugs',
 'DB Shoulder Shrugs**',
 'DB Upright Row',
 'Dead Bugs',
 'Decline Pushups',
 'Emphasis: UB Muscular Endurance & Technical Competency',
 'Emphasis: UB Muscular Endurance & Technical Comptency',
 'Frog, Pigeon, Happy Baby',
 'Full Curls',
 'Full Curls***',
 'Goblet RFE Lunge',
 'Goblet Squat',
 'Goblet Squats',
 'HK SA DB OH Press',
 'HK SA DB OH Press**',
 'High TRX Row',
 'High TRX Rows',
 'Hollow Holds',
 'Hypertrophy',
 'LB Warm Up (Bridges, Brid

In [187]:
sets

array([0., 1., 2., 3., 4., 5.])

In [188]:
reps.pop(0)

<bound method Series.unique of 0          Static Lunge
1                     0
2               Pushups
3                     0
4      SL Glute Bridges
5    Piriformis Stretch
Name: Squat, dtype: object>

In [189]:
for idx,i in enumerate(reps):
    reps[idx]=reps[idx]()

In [192]:
reps

[array(['If timed exercise ', 'enter time here', 0, 15, 20, 10, 60, 8, 12,
        'Reps', 30, 14, 13, 22, 15.33333333, 17], dtype=object),
 array(['If timed exercise ', 'enter time here', 0, 15, 10, 60, 8, 'Reps'],
       dtype=object),
 array(['If timed exercise ', 'enter time here', 0, 30, 10, 12, 60, 'Reps',
        8], dtype=object),
 array(['If timed exercise ', 'enter time here', 0, 10, 'Reps', 12, 30],
       dtype=object),
 array(['If timed exercise ', 'enter time here', 0, 10, 12, 60, 8, 'Reps',
        30], dtype=object),
 array(['If timed exercise ', 'enter time here', 0, 10, 'Reps', 8, 12, 15],
       dtype=object),
 array(['If timed exercise ', 'enter time here', 0, 10, 60, 6, 8, 'Reps',
        12, 15], dtype=object),
 array(['If timed exercise ', 'enter time here', 0, 5, 8, 12, 10, 'Reps',
        15, 12.6], dtype=object),
 array(['If timed exercise ', 'enter time here', 0, 8, 15, 10, 'Reps', 12],
       dtype=object),
 array(['If timed exercise ', 'enter time here', 0,

In [193]:
reps=[elem for sublist in reps for elem in sublist if isinstance(elem, (int, float))]

In [195]:
reps=np.unique(reps)

In [203]:
reps=np.delete(reps, 0)

In [280]:
reps

array([ 0,  4,  5,  6,  8, 10, 12, 13, 14, 15, 17, 20, 22, 30, 60])

In [205]:
sets=np.delete(sets, 0)

In [279]:
sets

array([0, 1, 2, 3, 4, 5])

In [278]:
exercises

array(['Alternating Reverse Lunge', 'Banded Goblet Pause Squat',
       'Banded Walks', 'Bench Press', 'Bench Press*', 'Bent Over Rows',
       "Bent Over T's", 'Bicep Curls', 'Bicycles',
       'Bilateral DB Bent Over Row', 'Bilateral DB Row*',
       'Bodyweight (Traveling)', 'Bodywieght Squats', 'Burpees',
       'Curl to OH Press', 'Curl to OH Press*', 'Curls',
       'DB Alternating Forward Lunge', 'DB Alternating Reverse Lunge',
       'DB Bench Press', 'DB Bench Press*', 'DB Curl to OH Press',
       'DB OH Press', 'DB OH Press*', 'DB Push Press',
       'DB Shoulder Shrugs', 'DB Shoulder Shrugs**', 'DB Upright Row',
       'Dead Bugs', 'Decline Pushups',
       'Emphasis: UB Muscular Endurance & Technical Competency',
       'Emphasis: UB Muscular Endurance & Technical Comptency',
       'Frog, Pigeon, Happy Baby', 'Full Curls', 'Full Curls***',
       'Goblet RFE Lunge', 'Goblet Squat', 'Goblet Squats',
       'HK SA DB OH Press', 'HK SA DB OH Press**', 'High TRX Row',
       

In [210]:
import random

selected_element_1 = random.choice(exercises)
selected_element_2 = random.choice(sets)
selected_element_3 = random.choice(reps)

result = (selected_element_1, int(selected_element_2), int(selected_element_3))
print(result)

('Up/Down Dog', 3, 17)


In [126]:
char_to_remove = [str(i) for i in (range(10))] + ['UB', 'LB', ':']

In [270]:
reps

[5, 8, 10, 12, 15]

In [271]:
reps=[elem for sublist in reps for elem in sublist if isinstance(elem, (int))]

TypeError: 'int' object is not iterable

In [127]:
char_to_remove

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'UB', 'LB', ':']

In [6]:
fuzz.

<module 'fuzzywuzzy' from '/Users/jaredperez/opt/miniconda3/envs/tf/lib/python3.10/site-packages/fuzzywuzzy/__init__.py'>

In [189]:
def prescribe_workout(client, goal):
    selection=pd.ExcelFile(f'/Users/jaredperez/Client Folders/{client}.xlsx')
    sheets=selection.sheet_names
    exercises=[]
    for sheet in sheets:
        df=pd.read_excel(selection, sheet_name=sheet, header=3)
        df=df.dropna(how='all')
        df=df.fillna(0)
        exercises.append(df.iloc[:,0].unique)#Because of misformatted data, make sure to pop 1st entry 
    exercises = [i() for i in exercises]
    exercises.pop(0)
    exercises=[elem for sublist in exercises for elem in sublist if isinstance(elem, (str))]
    char_to_remove = [str(i) for i in (range(10))] + ['UB', 'LB', ':']
    exercises=list(filter(lambda x: not any(y in x for y in char_to_remove), exercises))
    exercises = np.unique(exercises)
    
    set_selections=[]
    rep_selections=[]
    exercise_selections = []
    prescription=[]
    exercise = None
    for i in range(10):
        while exercise is None or any(fuzz.ratio(exercise, e) > 70 for e in exercise_selections):
            exercise = random.choice(exercises)
        exercise_selections.append(exercise)
        if 'plank' in exercise or 'Plank' in exercise or 'Mountain' in exercise:
            rep_selection = 30 #seconds
            set_selection =3
        elif goal == 'Endurance':
            rep_selection = 15
            set_selection=3
        elif goal=='Hypertrophy':
            rep_selection=random.choice([6,8,10,12])
            set_selection=random.choice([3,4,5])
        elif goal=='Strength':
            rep_selection=5
            set_selection=random.choice([3,4,5])
        else:
            rep_selection = 10
            set_selection=3
        rep_selections.append(rep_selection)
        set_selections.append(set_selection)

        prescriptions=np.asarray([exercise, set_selection, rep_selection]).reshape(-1,3)
        prescription.append(prescriptions)
    
    prescription=np.asarray(prescription).reshape(-1,3)
    prescription=pd.DataFrame(prescription, columns=['Exercise', 'Sets', 'Reps'])

    
    return prescription

In [190]:
prescribe_workout('Igor', 'Hypertrophy')

Exercise Sets Reps
0                       SL Glute Bridges    3   12
1                      Prone Incline T's    3   12
2                 Side Planks from Knees    3   30
3                Ankle over Knee Stretch    3    6
4  Prone Incline I, Y, T's (PNF stretch)    5    6
5                           DB Pullovers    5    6
6                            Clam Shells    4    6
7                                Stretch    4   10
8                              BW Lunges    5    8
9    Seated Banded Supinated Retractions    3   12

In [70]:
set_selections=[]
rep_selections=[]
for i in range(7):
    set_selection = random.choice(sets)
    set_selections.append(set_selection)
    rep_selection = random.choice(reps)
    rep_selections.append(rep_selection)

In [71]:
zipped_workout=zip(exercise_selections, set_selections,rep_selections)

In [144]:
x=[print(i) for i in zipped_workout]

In [146]:
exercise

'[Squat Jumps] DB Squat (DBs on shoulders)'

In [147]:
rep_selection

26

In [148]:
set_selection

2

In [166]:
example=np.asarray([exercise, set_selection, rep_selection]).reshape(1,-1)

In [159]:
example2=np.asarray([exercise, set_selection, rep_selection]).reshape(1,-1)

In [161]:
example2.shape

(1, 3)

In [170]:
concat=np.concatenate([example, example2], axis=0)

In [174]:
df=pd.DataFrame(concat, columns=['Prescription', 'Sets', 'Reps'])

In [175]:
df

Prescription Sets Reps
0  Plank Circuit (Side Plank->Plank->Side Plank)    4   19
1                     Pause Plate Squats w/Band     2   22

In [220]:
#Some rules...if exercise contains the words "plank" then reps should be greater than 20

#If exercise does not contain the words "plank" then reps between 5-15

for i in range(7):
    while exercise is None or any(fuzz.ratio(exercise, e) > 70 for e in exercise_selections):
        exercise = random.choice(exercises)
        if 'plank' in exercise or 'Plank' in exercise:
            rep_selection = 30 #seconds
        else:
            rep_selection = random.choice(reps)
    exercise_selections.append(exercise)
    set_selection = random.choice(sets)
    set_selections.append(set_selection)
    prescription=np.asarray([exercise_selections])
    
    

[['RDL' 'Dead Bugs' 'Bent Over Rows' 'Tricep Kickbacks' 'Squat Jumps'
  'Plank Circuit (Side Plank->Plank->Side Plank)' 'TRX Bicep Curls'
  'Side Plank' 'DB Alternating Forward Lunge' 'Hollow Holds'
  'TRX Low Row*' '[Squat Jumps] Offset Squats' 'SA DB Row'
  'Curl to OH Press']]


In [110]:
reps=[5,8,10,12,15]

In [117]:
rep_selections

[15, 23, 28, 22, 18, 27, 30, 29, 29, 24, 30, 18, 27, 21]

In [101]:
exercise

'Pullups*'

In [ ]:
from fuzzywuzzy import fuzz

In [230]:
exercise='Squat Thruster'
substrings = ['plank', 'Plank', 'Mountain']

for substring in substrings:
    if substring in exercise:
        rep_selection = 30 #seconds
        break
else:
    rep_selection = random.choice(reps)


In [231]:
rep_selection

15

In [245]:
goal='Hypertrophy'
set_selections=[]
rep_selections=[]
exercise_selections = []
prescription=[]
exercise = None
for i in range(7):
    while exercise is None or any(fuzz.ratio(exercise, e) > 70 for e in exercise_selections):
        exercise = random.choice(exercises)
    exercise_selections.append(exercise)
    if 'plank' in exercise or 'Plank' in exercise or 'Mountain' in exercise:
        rep_selection = 30 #seconds
    elif goal == 'Endurance':
        rep_selection = 15
        set_selection=3
    elif goal=='Hypertrophy':
        rep_selection=random.choice([6,8,10,12])
        set_selection=random.choice([3,4,5])
    elif goal=='Strength':
        rep_selection=5
        set_selection=random.choice([3,4,5])
    else:
        rep_selection = random.choice(reps)
        set_selection=random.choice(sets)
    rep_selections.append(rep_selection)
    set_selections.append(set_selection)

    prescriptions=np.asarray([exercise, set_selection, rep_selection]).reshape(-1,3)
    prescription.append(prescriptions)
    
prescription=np.asarray(prescription).reshape(-1,3)
prescription=pd.DataFrame(prescription, columns=['Exercise', 'Sets', 'Reps'])

In [246]:
prescription

Exercise Sets Reps
0    Pushup Position Arm Raises    3    6
1                DB Upright Row    5    6
2                    RFE Lunges    5   12
3                 Bent Over T's    5   10
4                   Bicep Curls    4   12
5                     TRX Rows     5   12
6  Seated DB OH Press (Z-press)    3   12

In [ ]:
"""
I need to drop elements from the larger exercise list that contain the strings [UB, LB, :]

"""

In [50]:
exercise_selections

['High TRX Row',
 'TRX Pushup',
 'SIde Plank w/Press',
 'DB Shoulder Shrugs**',
 'Bilateral DB Bent Over Row',
 'TRX Low Rows',
 'HK SA DB OH Press']

In [ ]:
def prescription(client):
    files = glob.glob('/Users/jaredperez/Client Folders/*.xlsx')
    selection=f'/Users/jaredperez/Client Folders/{client}.xlsx'
    workbook = openpyxl.load_workbook(selection)

In [16]:
def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

In [18]:
ALLOWED_EXTENSIONS='xlsx'

In [27]:
files=glob.glob('/Users/jaredperez/Client Folders/*')

In [28]:
files

['/Users/jaredperez/Client Folders/Dimitri.xlsx',
 '/Users/jaredperez/Client Folders/Masha.xlsx',
 '/Users/jaredperez/Client Folders/Misha.xlsx',
 '/Users/jaredperez/Client Folders/Intro_to_Autoencoders.ipynb',
 '/Users/jaredperez/Client Folders/Anya.xlsx',
 '/Users/jaredperez/Client Folders/Arne.xlsx',
 '/Users/jaredperez/Client Folders/Max.xlsx',
 '/Users/jaredperez/Client Folders/Dino.xlsx',
 '/Users/jaredperez/Client Folders/Ilya.xlsx',
 '/Users/jaredperez/Client Folders/Igor.xlsx',
 '/Users/jaredperez/Client Folders/Nick_Mary.xlsx',
 '/Users/jaredperez/Client Folders/Daniel Murphy.xlsx',
 '/Users/jaredperez/Client Folders/Yelena.xlsx',
 '/Users/jaredperez/Client Folders/Shawn.xlsx']

In [29]:
allowed_file(files[3])

False

In [35]:
schema="""
DROP TABLE IF EXISTS clients;

CREATE TABLE clients (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    intensity TEXT NOT NULL,
    goal TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);"""

In [38]:
conn = sqlite3.connect('database.db')

In [ ]:
conn.executescript

In [36]:
conn = sqlite3.connect('database.db')
    conn.executescript(schema)
    conn.close()

def get_db_connection():
    conn = sqlite3.connect('database.db')
    conn.row_factory = sqlite3.Row
    return conn

In [37]:
init_db()

In [ ]:
def get_excel_data(conn, name):
    # Get the Excel file name based on the name
    file_name = f"{name}.xlsx"
    
    # Read the Excel file from the database into a pandas DataFrame
    df = pd.read_excel(conn, file_name)
    
    # Convert the DataFrame to a list of dictionaries (each dict represents a row in the Excel file)
    data = df.to_dict('records')
    
    return data


In [39]:
files

['/Users/jaredperez/Client Folders/Dimitri.xlsx',
 '/Users/jaredperez/Client Folders/Masha.xlsx',
 '/Users/jaredperez/Client Folders/Misha.xlsx',
 '/Users/jaredperez/Client Folders/Intro_to_Autoencoders.ipynb',
 '/Users/jaredperez/Client Folders/Anya.xlsx',
 '/Users/jaredperez/Client Folders/Arne.xlsx',
 '/Users/jaredperez/Client Folders/Max.xlsx',
 '/Users/jaredperez/Client Folders/Dino.xlsx',
 '/Users/jaredperez/Client Folders/Ilya.xlsx',
 '/Users/jaredperez/Client Folders/Igor.xlsx',
 '/Users/jaredperez/Client Folders/Nick_Mary.xlsx',
 '/Users/jaredperez/Client Folders/Daniel Murphy.xlsx',
 '/Users/jaredperez/Client Folders/Yelena.xlsx',
 '/Users/jaredperez/Client Folders/Shawn.xlsx']

In [ ]:
xlsxs=[]
for i in files:
    xlsx=pd.ExcelFile(f'/Users/jaredperez/Client Folders/Ilya.xlsx')

In [2]:
import psycopg2

In [5]:
df = pd.read_excel(f'/Users/jaredperez/Client Folders/Ilya.xlsx')

In [6]:
df

2021-05-24 00:00:00            Unnamed: 1                 SRPE  \
0                  NaN             LB Warmup                  NaN   
1                  NaN         Plank Circuit                    5   
2                  NaN               Pushups                    9   
3                  NaN           Bench Press  2021-06-09 00:00:00   
4                  NaN           DB OH Press  2021-07-08 00:00:00   
5                  NaN  Standing Snow Angels                  9.5   
6                  NaN               TRX Row  2021-04-05 00:00:00   
7                  NaN                 Squat                  NaN   
8                  NaN                   NaN                  NaN   

       Unnamed: 3 2021-06-01 00:00:00     Unnamed: 5            Unnamed: 6  \
0             NaN          UB Warm Up             3x                   NaN   
1            3x30       Plank Circuit       3x30 sec                   NaN   
2            3x10               Squat    3x10 @20,30                   NaN   
3   3x15,12,8 @25        Static Lunge  3x10 EL @10lb  Banded Walks 3x1 min   
4  3x5,6, 8 @5lbs                 NaN            NaN                   NaN   
5      3x10 @5lbs             Pushups   4x10,10,10,6                   NaN   
6      3x10,12,10                 NaN            NaN                   NaN   
7             NaN    SL Glute Bridges         3x10EL                   NaN   
8             NaN  Piriformis Stretch    1x30 sec ES                   NaN   

      2021-06-08 00:00:00                Unnamed: 8  \
0              UB Warm Up                       NaN   
1           Plank Circuit                       NaN   
2       SA DB Bench Press  3x10 @25lbs, 1x10 @30lbs   
3               SA DB Row               3x10 @30lbs   
4          SA DB OH Press               3x10 @15lbs   
5             TRX Low Row                3x15,15,11   
6            TRX High Row                      3x10   
7  Full ROM Forward Raise                3x10 @5lbs   
8   Standing Shoulder T's                3x10 @5lbs   

                              Unnamed: 9           Unnamed: 10  
0                                    NaN                   NaN  
1                                    NaN                   NaN  
2                             Manageable  Could do 3x10 @30lbs  
3  technical (back and drive elbow back)                   NaN  
4                             Max at end                   NaN  
5                                    NaN                   NaN  
6                                    NaN                   NaN  
7                                    NaN                   NaN  
8                                    NaN                   NaN

In [7]:
xlsx=pd.ExcelFile(f'/Users/jaredperez/Client Folders/Ilya.xlsx')
sheets=xlsx.sheet_names

In [8]:
sheets

['Skip',
 'Block 1',
 'Block 2',
 'Block 3',
 'September',
 'Oct',
 'Nov-Dec',
 'Jan 2022',
 'Feb 2022',
 'March',
 'April',
 'May',
 'Traveling BW Block',
 'August-Recondition',
 'September 2022',
 'October',
 'November-December',
 'Recondition']

In [3]:
df = pd.read_excel(f'/Users/jaredperez/Client Folders/Test.xlsx')

In [4]:
df=df.dropna(how='all')
df=df.fillna(0)

In [5]:
df

Exercise  Weight  Reps
0    Bench     120    10
1   Squats     100    10
2  Pullups      50    10

In [6]:
data = df.to_csv(index=False).encode()

In [7]:
data

b'Exercise,Weight,Reps\nBench,120,10\nSquats,100,10\nPullups,50,10\n'

In [88]:
conn = psycopg2.connect(
    host="localhost",
    database="clients",
    user="jaredp",
    password="secret"
)


In [33]:
with conn.cursor() as cur:
    cur.execute("""
    SELECT * FROM excel_files;""")
    conn.commit()

In [91]:
import io

In [86]:
# insert binary data into PostgreSQL
with conn.cursor() as cur:
    cur.execute("""
        INSERT INTO excel_files (file_name, sheet_name, data)
        VALUES (%s, %s, %s);
    """, ('Test', 'Block 1', psycopg2.Binary(data)))
    conn.commit()


In [105]:
data[0][0]

In [97]:
data = cur.fetchone()

In [109]:
print(data.decode('utf-8'))

AttributeError: 'memoryview' object has no attribute 'decode'

In [110]:
file_data=bytes(data)

In [113]:
file_data

b'Exercise,Weight,Reps\nBench,120,10\nSquats,100,10\nPullups,50,10\n'

In [114]:
data_str = file_data.decode('utf-8')

In [115]:
data_str

'Exercise,Weight,Reps\nBench,120,10\nSquats,100,10\nPullups,50,10\n'

In [116]:
data_file = io.StringIO(data_str)

In [117]:
data_file

In [120]:
csv_file=io.StringIO(data_str)

In [121]:
csv_file

In [122]:
df=pd.read_csv(csv_file)

In [123]:
df

Exercise  Weight  Reps
0    Bench     120    10
1   Squats     100    10
2  Pullups      50    10

In [112]:
cur = conn.cursor()
cur.execute("SELECT data FROM excel_files WHERE id = 8")  
data = cur.fetchall()[0][0]

# Decode the data and read it into a Pandas DataFrame
df = pd.read_excel(io.BytesIO(file_data))

ValueError: Excel file format cannot be determined, you must specify an engine manually.

In [124]:
conn.close()

In [1034]:
arrays

[array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([48, 48, 48, 48, 48, 48, 48]),
 array([ 10,   2,  48,   4,  60,  60,  60,  60, 120]),
 array([48, 48, 48, 48, 48, 48, 48, 60]),
 array([ 10,   2,  40, 120, 120,  60,  60,   4,  48,   1]),
 array([48, 48, 48, 48, 48, 48, 90]),
 array([ 10,   2,  40,   4,  40,  40,  40,  40, 120]),
 array([48, 48, 48, 48, 48, 48, 48, 48]),
 array([ 10,   2,  40, 120, 120,  40,  40,   4,  40,   1]),
 array([48, 48, 48, 48, 48, 48, 48, 48]),
 array([ 10,   2,  40,   4,  60,  60,  60,  60, 120]),
 array([48, 48, 48, 48, 48, 48, 48, 40]),
 array([10,  2, 20, 90, 90, 30, 30,  3, 30,  1]),
 array([48, 48, 48, 48, 48, 48, 48, 48]),
 array([10,  2, 30,  3, 30, 30, 30, 30, 90]),
 array([48, 48, 48, 48, 48, 48, 48, 40]),
 array([10,  2, 30, 90, 90, 30, 30,  3, 30]),
 array([48, 48, 48, 48, 48, 48]),
 array([ 10,   2,  40,  40,  40,  40,  40, 120,  40]),
 array([48, 48, 48, 48, 48, 48, 48]),
 array([10,  2, 30, 30, 30, 30, 30, 90, 30]),
 array([48, 48

# Below is focusing on backend grabbing of workout based on logic

In [8]:
Igor=openpyxl.load_workbook(f'/Users/jaredperez/Client Folders/Igor.xlsx')

In [9]:
sheet=Igor['June']

In [25]:
sheet

<Worksheet "June">

In [11]:
for row in sheet.iter_rows(max_row=30, max_col=1):
    for cell in row:
        print(cell.value)

Exercise
None
None
6/12-6/18 (M)
None
Workout 1-UB Lifts
Foam Roll
Banded Retractions/Over and Back/BTN Press
Banded Walks
Prone Incline I, Y, T's (PNF stretch)
Prone Incline OH Press
SA Farmers Walks
DB Pullovers
None
T-Spine Stretch-->LB Stretches
None
Workout 2-GVC-Core
Roll Out
LB Warm Up (Bridge, March, Leg Extension)
Clam Shells
Abductions
Opposit Arm/Leg reach
Planks
Side Planks from knees
Banded Walks
None
SL Glute bridges
Stretch
None
None


In [12]:
sheet['A1']='Exercise'

In [140]:
print(os.getcwd())

/Users/jaredperez/Portfolio Project 2 Client Workout Selection Program


In [141]:
Igor.save("/Users/jaredperez/Client Folders/Igor.xlsx")

In [13]:
test_data=[]
for row in sheet.iter_rows(max_row=30, max_col=1):
    for cell in row:
        if cell.value is None:
            pass
    test_data.append(cell.value)

In [14]:
test_data

['Exercise',
 None,
 None,
 '6/12-6/18 (M)',
 None,
 'Workout 1-UB Lifts',
 'Foam Roll',
 'Banded Retractions/Over and Back/BTN Press',
 'Banded Walks',
 "Prone Incline I, Y, T's (PNF stretch)",
 'Prone Incline OH Press',
 'SA Farmers Walks',
 'DB Pullovers',
 None,
 'T-Spine Stretch-->LB Stretches',
 None,
 'Workout 2-GVC-Core',
 'Roll Out',
 'LB Warm Up (Bridge, March, Leg Extension)',
 'Clam Shells',
 'Abductions',
 'Opposit Arm/Leg reach',
 'Planks',
 'Side Planks from knees',
 'Banded Walks',
 None,
 'SL Glute bridges',
 'Stretch',
 None,
 None]

In [15]:
workout=[]
start_row = 0
done=False

for row in sheet.iter_rows(max_row=30, max_col=1):
    for cell in row:
        if "workout" in str(cell.value).lower():
            start_row = cell.row
        if start_row > 0 and cell.row >= start_row and cell.row <= start_row + 7:
            workout.append(cell.value)
        if cell.row > start_row + 7:
            done=True
            break
        
    if done:
        break

In [16]:
workout

['Workout 1-UB Lifts',
 'Foam Roll',
 'Banded Retractions/Over and Back/BTN Press',
 'Banded Walks',
 "Prone Incline I, Y, T's (PNF stretch)",
 'Prone Incline OH Press',
 'SA Farmers Walks',
 'DB Pullovers']

In [17]:
exercises=[]
start_row = 0
done=False

for row in sheet.iter_rows(max_col=3):
    values = []
    for cell in row:
        values.append(cell.value)
        if "workout" in str(cell.value).lower():
            start_row = cell.row
        if start_row > 0 and cell.row >= start_row and cell.row <= start_row + 6:
            if len(values) == 3:
                exercises.append((values[0], values[1], values[2]))
            
        

exercises

[('Workout 1-UB Lifts', '95-100%=0-1 reps left', 'Bands (XH=1.3 modifier'),
 ('Foam Roll', '1x', None),
 ('Banded Retractions/Over and Back/BTN Press', '2x', None),
 ('Banded Walks', '3x10', 1),
 ("Prone Incline I, Y, T's (PNF stretch)", '3x10', 2.5),
 ('Prone Incline OH Press', '3x10', 2.5),
 ('SA Farmers Walks', '2x30 sec', 15),
 ('Workout 2-GVC-Core', None, None),
 ('Roll Out', None, None),
 ('LB Warm Up (Bridge, March, Leg Extension)', '2x', None),
 ('Clam Shells', '3x10', None),
 ('Abductions', '3x10 ', None),
 ('Opposit Arm/Leg reach', '3x30 sec', None),
 ('Planks', '3x30 sec', None),
 ('Workout 1-UB Lifts', '95-100%=0-1 reps left', 'Bands (XH=1.3 modifier'),
 ('Foam Roll', '1x', None),
 ('Banded Retractions/Over and Back/BTN Press', '2x', 1),
 ('Banded Walks', '3x10', 1),
 ('SL Glute Bridges', '3x10', 1),
 (None, None, None),
 (None, None, None),
 ('Workout 2-GVC-Core', None, None),
 ('Roll Out', None, None),
 ('LB Warm Up (Bridge, March, Leg Extension)', '2x', None),
 ('Banded 

In [18]:
workouts = []
current_workout = []

start = 0
for idx, row in enumerate(exercises):
    if row[0] is None:
        continue
    if "workout" in str(row[0]).lower():
        if current_workout:
            workouts.append(current_workout)
        current_workout = []
        start = idx
    current_workout.append(row)
stop = idx

# Append the last workout to the list of workouts
if current_workout:
    workouts.append(current_workout)


In [19]:
workouts

[[('Workout 1-UB Lifts', '95-100%=0-1 reps left', 'Bands (XH=1.3 modifier'),
  ('Foam Roll', '1x', None),
  ('Banded Retractions/Over and Back/BTN Press', '2x', None),
  ('Banded Walks', '3x10', 1),
  ("Prone Incline I, Y, T's (PNF stretch)", '3x10', 2.5),
  ('Prone Incline OH Press', '3x10', 2.5),
  ('SA Farmers Walks', '2x30 sec', 15)],
 [('Workout 2-GVC-Core', None, None),
  ('Roll Out', None, None),
  ('LB Warm Up (Bridge, March, Leg Extension)', '2x', None),
  ('Clam Shells', '3x10', None),
  ('Abductions', '3x10 ', None),
  ('Opposit Arm/Leg reach', '3x30 sec', None),
  ('Planks', '3x30 sec', None)],
 [('Workout 1-UB Lifts', '95-100%=0-1 reps left', 'Bands (XH=1.3 modifier'),
  ('Foam Roll', '1x', None),
  ('Banded Retractions/Over and Back/BTN Press', '2x', 1),
  ('Banded Walks', '3x10', 1),
  ('SL Glute Bridges', '3x10', 1)],
 [('Workout 2-GVC-Core', None, None),
  ('Roll Out', None, None),
  ('LB Warm Up (Bridge, March, Leg Extension)', '2x', None),
  ('Banded Bridge Abduction

In [20]:
dfs=[pd.DataFrame(i[1:], columns=['Exercise', 'Prescription', 'Weight']) for i in workouts]

In [21]:
dfs[2]

Exercise Prescription  Weight
0                                   Foam Roll           1x     NaN
1  Banded Retractions/Over and Back/BTN Press           2x     1.0
2                                Banded Walks         3x10     1.0
3                            SL Glute Bridges         3x10     1.0

In [274]:
path=glob.glob('/Users/jaredperez/Client Folders/*')

In [276]:
allowed_extenstions=".xlsx"
path

['/Users/jaredperez/Client Folders/Dimitri.xlsx',
 '/Users/jaredperez/Client Folders/Masha.xlsx',
 '/Users/jaredperez/Client Folders/Misha.xlsx',
 '/Users/jaredperez/Client Folders/Intro_to_Autoencoders.ipynb',
 '/Users/jaredperez/Client Folders/Anya.xlsx',
 '/Users/jaredperez/Client Folders/Arne.xlsx',
 '/Users/jaredperez/Client Folders/Max.xlsx',
 '/Users/jaredperez/Client Folders/Dino.xlsx',
 '/Users/jaredperez/Client Folders/Test.xlsx',
 '/Users/jaredperez/Client Folders/Ilya.xlsx',
 '/Users/jaredperez/Client Folders/Igor.xlsx',
 '/Users/jaredperez/Client Folders/Nick_Mary.xlsx',
 '/Users/jaredperez/Client Folders/Daniel Murphy.xlsx',
 '/Users/jaredperez/Client Folders/Yelena.xlsx',
 '/Users/jaredperez/Client Folders/Shawn.xlsx']

In [57]:
def grab_block(client_name):
    file=openpyxl.load_workbook(f'/Users/jaredperez/Client Folders/{client_name}.xlsx')
    all_sheetnames = file.sheetnames
    valid_sheetnames = [name for name in all_sheetnames if "skip" not in name]
    sheet_name = random.choice(valid_sheetnames)
    sheet=file[sheet_name]
    exercises=[]
    start_row = 0

    for row in sheet.iter_rows(max_col=3):
        values = []
        for cell in row:
            values.append(cell.value)
            if "workout" in str(cell.value).lower():
                start_row = cell.row
            if start_row > 0 and cell.row >= start_row and cell.row <= start_row + 6:
                if len(values) == 3:
                    exercises.append((values[0], values[1], values[2]))
                
    workouts = []
    current_workout = []

    start = 0
    for idx, row in enumerate(exercises):
        if row[0] is None:
            continue
        if "workout" in str(row[0]).lower():
            if current_workout:
                workouts.append(current_workout)
            current_workout = []
            start = idx
        current_workout.append(row)
    stop = idx

    if current_workout:
        workouts.append(current_workout)
        
    dfs=[pd.DataFrame(i[1:], columns=['Exercise', 'Prescription', 'Weight']) for i in workouts]
    
    return dfs

In [378]:
grab_block('Max')[0]

Exercise Prescription  Weight
0                  J-Jacks         1x50     NaN
1                Foam Roll           1x     NaN
2          UpWard/Down Dog           2x     NaN
3        Mountain Climbers         3x30     1.0
4             Squat Jumps          3x10     1.0
5  Reverse Lunge-->Step Up      3x10 ES     1.0

In [670]:
def grab_all_workouts(client_name):
    file=openpyxl.load_workbook(f'/Users/jaredperez/Client Folders/{client_name}.xlsx')
    all_sheetnames = file.sheetnames
    valid_sheetnames = [name for name in all_sheetnames if "skip" not in name]
    sheets=[file[i] for i in valid_sheetnames]
    exercises=[]
    start_row = 0

    for block in sheets:
        for row in block.iter_rows(max_col=3):
            values = []
            for cell in row:
                values.append(cell.value)
                if "workout" in str(cell.value).lower():
                    start_row = cell.row
                if start_row > 0 and cell.row >= start_row and cell.row <= start_row + 6:
                    if len(values) == 3:
                        exercises.append((values[0], values[1], values[2]))
                
    workouts = []
    current_workout = []

    start = 0
    for idx, row in enumerate(exercises):
        if row[0] is None:
            continue
        if "workout" in str(row[0]).lower():
            if current_workout:
                workouts.append(current_workout)
            current_workout = []
            start = idx
        current_workout.append(row)
    stop = idx

    if current_workout:
        workouts.append(current_workout)
        
    dfs = [pd.DataFrame(i[1:], columns=['Exercise', 'Prescription', 'Weight']) for i in workouts]
    for df in dfs:
        df['Weight'] = df['Weight'].fillna(1)
        try:
            df['Weight']=df['Weight'].astype(dtype='float64')
        except:
            pass

    
    return dfs

In [790]:
dfs=grab_all_workouts('Igor')

In [739]:
dfs

[                         Exercise Prescription  Weight
 0                        Roll Out           10     1.0
 1  Lb Warm Up (no arms dead bugs)           2x     1.0
 2               Quad Contractions        2x10      1.0
 3                          Planks     3x30 sec     1.0
 4          Side Planks from knees     2x30 sec     1.0,
                       Exercise Prescription  Weight
 0                     Roll Out         None     1.0
 1  Lb Warm Up (leg extensions)           2x     1.0
 2     Banded Bridge Abductions         None     1.0
 3                       Planks     3x30 sec     1.0
 4       Side Planks from knees     2x30 sec     1.0,
                       Exercise Prescription  Weight
 0                     Roll Out         None     1.0
 1  Lb Warm Up (leg extensions)           3x     1.0
 2     Banded Bridge Abductions         3x10     1.0
 3            Quad Contractions        3x10      1.0
 4                       Planks     3x30 sec     1.0
 5       Side Planks from 

In [791]:
for idx,df in enumerate(dfs):
    if df['Weight'].dtype != 'float64':
        dfs.pop(idx)


In [792]:
len(dfs)

62

# Started working on calculating of volume load from prescription using Regex

In [136]:
s = '3x60'
parts = [part.strip() for part in s.split('x')]
print(parts)  # Output: ['3', '60']


['3', '60']


In [149]:
import re

s = ['3x60 sec','3x60']
parts = [re.findall(r'^(\d+)x(\d+)$', i) for i in s]
print(parts)  # Output: ('3', '60')


[[], [('3', '60')]]


In [158]:
s='3x30 '
parts = re.findall(r'^(\d+)x(\d+) $', s)
print(parts)  # Output: ('3', '60')

[('3', '30')]


In [424]:
inputs

['1x',
 '2x',
 '3x60 sec',
 '3x60 sec',
 '3x30 (circuit)',
 '3x15',
 '3x15',
 '3x60 sec']

In [425]:
import re

pattern = r'^(\d+)x(\d+)?(?:\s*sec|\s*\(\s*\w*\s*\))?'

parts_full=[]
for s in inputs:
    parts = re.findall(pattern, s)
    parts_full.append(parts)
    print(parts)


[('1', '')]
[('2', '')]
[('3', '60')]
[('3', '60')]
[('3', '30')]
[('3', '15')]
[('3', '15')]
[('3', '60')]


In [426]:
parts_full

[[('1', '')],
 [('2', '')],
 [('3', '60')],
 [('3', '60')],
 [('3', '30')],
 [('3', '15')],
 [('3', '15')],
 [('3', '60')]]

In [427]:
arr=np.array(parts_full).reshape(-1,2)

In [428]:
arr

array([['1', ''],
       ['2', ''],
       ['3', '60'],
       ['3', '60'],
       ['3', '30'],
       ['3', '15'],
       ['3', '15'],
       ['3', '60']], dtype='<U2')

In [347]:
arr[0][1].replace('','1')

'1'

In [348]:
arr=np.where(arr=='','1',arr)

In [349]:
arr

array([['1', '1'],
       ['2', '1'],
       ['3', '60'],
       ['3', '60'],
       ['3', '30'],
       ['3', '15'],
       ['3', '15'],
       ['3', '60']], dtype='<U2')

In [350]:
arr_df=pd.DataFrame(arr)

In [354]:
arr_df=arr_df.astype(dtype='int')

In [194]:
s="sx3000"
parts=re.findall(r"^[A-Za-z]x\d+", s)

In [195]:
parts

['sx3000']

In [461]:
prescriptions=[i['Prescription'] for i in dfs]
prescriptions=[i.dropna() for i in prescriptions]

In [462]:
prescriptions

[0      1x
 1      2x
 2    2x10
 3    2x10
 4    3x10
 5    3x10
 Name: Prescription, dtype: object,
 1          2x
 2     3x10 ES
 3       3x10 
 4    3x30 sec
 5    3x30 sec
 6    3x60 sec
 Name: Prescription, dtype: object,
 0      1x
 1      2x
 2    2x10
 3    2x10
 4    3x10
 5    3x10
 6    3x10
 Name: Prescription, dtype: object,
 1          2x
 2        3x10
 3       3x10 
 4    3x30 sec
 5    3x30 sec
 6    3x60 sec
 7        3x15
 Name: Prescription, dtype: object,
 0      1x
 1      2x
 2    2x10
 3    2x10
 4    3x10
 5    3x10
 6    3x10
 7    3x15
 Name: Prescription, dtype: object,
 1          2x
 2        3x10
 3       3x10 
 4    3x30 sec
 5    3x30 sec
 6    3x60 sec
 7        3x15
 Name: Prescription, dtype: object,
 1          2x
 2        3x10
 3       3x10 
 4    3x30 sec
 5    3x30 sec
 6        3x15
 Name: Prescription, dtype: object,
 1          2x
 2        3x10
 3       3x10 
 4    3x30 sec
 5    3x30 sec
 6        3x15
 Name: Prescription, dtype: object,
 

In [463]:
prescriptions=[i.values for i in prescriptions]

In [464]:
inputs=prescriptions

In [465]:
inputs

[array(['1x', '2x', '2x10', '2x10', '3x10', '3x10'], dtype=object),
 array(['2x', '3x10 ES', '3x10 ', '3x30 sec', '3x30 sec', '3x60 sec'],
       dtype=object),
 array(['1x', '2x', '2x10', '2x10', '3x10', '3x10', '3x10'], dtype=object),
 array(['2x', '3x10', '3x10 ', '3x30 sec', '3x30 sec', '3x60 sec', '3x15'],
       dtype=object),
 array(['1x', '2x', '2x10', '2x10', '3x10', '3x10', '3x10', '3x15'],
       dtype=object),
 array(['2x', '3x10', '3x10 ', '3x30 sec', '3x30 sec', '3x60 sec', '3x15'],
       dtype=object),
 array(['2x', '3x10', '3x10 ', '3x30 sec', '3x30 sec', '3x15'],
       dtype=object),
 array(['2x', '3x10', '3x10 ', '3x30 sec', '3x30 sec', '3x15'],
       dtype=object),
 array(['1x', '2x', '2x10', '2x10', '3x10', '3x10', '3x10', '3x10'],
       dtype=object),
 array(['2x', '3x30 sec', '3x30 sec', '3x30 sec', '3x30 sec', '3x60 sec'],
       dtype=object),
 array(['1x', '2x', '2x10', '2x10', '3x10', '3x10', '3x10', '3x10'],
       dtype=object),
 array(['2x', '3x10', '3x

In [516]:
pattern = r'^(\d+)x(\d+)?(?:\s*sec|\s*\(\s*\w*\s*\)|\s*min|\s*@|)?'
outputs = []
for arr in inputs:
    parts_full = []
    for s in arr:
        parts = re.findall(pattern, s)
        parts_full.append(parts)
    outputs.append(parts_full)

In [485]:
len(outputs)

58

In [515]:
len(outputs)

57

In [525]:
outputs_fixed = [item for item in outputs if item != [[]]]

In [535]:
outputs_fixed

[[[('1', '')],
  [('2', '')],
  [('2', '10')],
  [('2', '10')],
  [('3', '10')],
  [('3', '10')]],
 [[('2', '')],
  [('3', '10')],
  [('3', '10')],
  [('3', '30')],
  [('3', '30')],
  [('3', '60')]],
 [[('1', '')],
  [('2', '')],
  [('2', '10')],
  [('2', '10')],
  [('3', '10')],
  [('3', '10')],
  [('3', '10')]],
 [[('2', '')],
  [('3', '10')],
  [('3', '10')],
  [('3', '30')],
  [('3', '30')],
  [('3', '60')],
  [('3', '15')]],
 [[('1', '')],
  [('2', '')],
  [('2', '10')],
  [('2', '10')],
  [('3', '10')],
  [('3', '10')],
  [('3', '10')],
  [('3', '15')]],
 [[('2', '')],
  [('3', '10')],
  [('3', '10')],
  [('3', '30')],
  [('3', '30')],
  [('3', '60')],
  [('3', '15')]],
 [[('2', '')],
  [('3', '10')],
  [('3', '10')],
  [('3', '30')],
  [('3', '30')],
  [('3', '15')]],
 [[('2', '')],
  [('3', '10')],
  [('3', '10')],
  [('3', '30')],
  [('3', '30')],
  [('3', '15')]],
 [[('1', '')],
  [('2', '')],
  [('2', '10')],
  [('2', '10')],
  [('3', '10')],
  [('3', '10')],
  [('3', '10')]

In [541]:
fixed_outputs=[np.array(i).reshape(-1,2) for i in outputs_fixed]

In [542]:
fixed_outputs

[array([['1', ''],
        ['2', ''],
        ['2', '10'],
        ['2', '10'],
        ['3', '10'],
        ['3', '10']], dtype='<U2'),
 array([['2', ''],
        ['3', '10'],
        ['3', '10'],
        ['3', '30'],
        ['3', '30'],
        ['3', '60']], dtype='<U2'),
 array([['1', ''],
        ['2', ''],
        ['2', '10'],
        ['2', '10'],
        ['3', '10'],
        ['3', '10'],
        ['3', '10']], dtype='<U2'),
 array([['2', ''],
        ['3', '10'],
        ['3', '10'],
        ['3', '30'],
        ['3', '30'],
        ['3', '60'],
        ['3', '15']], dtype='<U2'),
 array([['1', ''],
        ['2', ''],
        ['2', '10'],
        ['2', '10'],
        ['3', '10'],
        ['3', '10'],
        ['3', '10'],
        ['3', '15']], dtype='<U2'),
 array([['2', ''],
        ['3', '10'],
        ['3', '10'],
        ['3', '30'],
        ['3', '30'],
        ['3', '60'],
        ['3', '15']], dtype='<U2'),
 array([['2', ''],
        ['3', '10'],
        ['3', '10'],
      

In [549]:
test=fixed_outputs[2]

In [548]:
fixed_outputs[2]

array([['1', ''],
       ['2', ''],
       ['2', '10'],
       ['2', '10'],
       ['3', '10'],
       ['3', '10'],
       ['3', '10']], dtype='<U2')

In [551]:
arrays=[np.where(i=='','1',i).astype(dtype='int') for i in fixed_outputs]

In [553]:
arrays

[array([[ 1,  1],
        [ 2,  1],
        [ 2, 10],
        [ 2, 10],
        [ 3, 10],
        [ 3, 10]]),
 array([[ 2,  1],
        [ 3, 10],
        [ 3, 10],
        [ 3, 30],
        [ 3, 30],
        [ 3, 60]]),
 array([[ 1,  1],
        [ 2,  1],
        [ 2, 10],
        [ 2, 10],
        [ 3, 10],
        [ 3, 10],
        [ 3, 10]]),
 array([[ 2,  1],
        [ 3, 10],
        [ 3, 10],
        [ 3, 30],
        [ 3, 30],
        [ 3, 60],
        [ 3, 15]]),
 array([[ 1,  1],
        [ 2,  1],
        [ 2, 10],
        [ 2, 10],
        [ 3, 10],
        [ 3, 10],
        [ 3, 10],
        [ 3, 15]]),
 array([[ 2,  1],
        [ 3, 10],
        [ 3, 10],
        [ 3, 30],
        [ 3, 30],
        [ 3, 60],
        [ 3, 15]]),
 array([[ 2,  1],
        [ 3, 10],
        [ 3, 10],
        [ 3, 30],
        [ 3, 30],
        [ 3, 15]]),
 array([[ 2,  1],
        [ 3, 10],
        [ 3, 10],
        [ 3, 30],
        [ 3, 30],
        [ 3, 15]]),
 array([[ 1,  1],
        [ 2,

In [554]:
arrays=[i[:,0]*i[:,1] for i in arrays]

In [561]:
len(arrays)

57

In [566]:
dfs[31]

Exercise Prescription  Weight
0         Foam Roll           1x     0.0
1      Frog Stretch           2x     0.0
2      Banded Walks         3x10     1.0
3            Squats         3x10    10.0
4     Static Lunges         3x10     5.0
5  SA Farmers Walks     3x30 sec    15.0
6  SL Glute Bridges         3x15     1.0
7            Planks     3x30 sec     1.0

In [565]:
len(dfs)

57

# Drop the none's and finish a way to calculate VL to build second logic based function based off of Volume Load

In [682]:
dfs[2]

Exercise Prescription  Weight
0                     Roll Out         None     1.0
1  Lb Warm Up (leg extensions)           3x     1.0
2     Banded Bridge Abductions         3x10     1.0
3            Quad Contractions        3x10      1.0
4                       Planks     3x30 sec     1.0
5       Side Planks from knees     3x30 sec     1.0

In [581]:
arrays[2]

array([ 1,  2, 20, 20, 30, 30, 30])

In [795]:
test=dfs[0]

In [809]:
dfs[0]

Exercise Prescription  Weight
0                        Roll Out           10     1.0
1  Lb Warm Up (no arms dead bugs)           2x     1.0
2               Quad Contractions        2x10      1.0
3                          Planks     3x30 sec     1.0
4          Side Planks from knees     2x30 sec     1.0

In [810]:
if dfs[0]['Prescription'].apply(lambda x: isinstance(x, int)).any():
    dfs[0]['Prescription'] = dfs[0]['Prescription'].astype(str)


In [804]:
test['Prescription']

0          10
1          2x
2       2x10 
3    3x30 sec
4    2x30 sec
Name: Prescription, dtype: object

I have some dfs that have a None in weight and all the arrays have removed the None values. So I need to remove the None in the dfs to brodcast across

In [811]:
pres_weight=[i[['Prescription', 'Weight']] for i in dfs]

In [812]:
pres_weight

[  Prescription  Weight
 0           10     1.0
 1           2x     1.0
 2        2x10      1.0
 3     3x30 sec     1.0
 4     2x30 sec     1.0,
   Prescription  Weight
 0         None     1.0
 1           2x     1.0
 2         None     1.0
 3     3x30 sec     1.0
 4     2x30 sec     1.0,
   Prescription  Weight
 0         None     1.0
 1           3x     1.0
 2         3x10     1.0
 3        3x10      1.0
 4     3x30 sec     1.0
 5     3x30 sec     1.0,
   Prescription  Weight
 0         None     1.0
 1           3x     1.0
 2         3x10     1.0
 3        3x10      1.0
 4     3x30 sec     1.0
 5     3x30 sec     1.0,
   Prescription  Weight
 0           3x     1.0
 1         3x10     1.0
 2        3x10      1.0
 3     3x30 sec     1.0
 4     3x30 sec     1.0,
   Prescription  Weight
 0           1x     1.0
 1           2x    20.0
 2         2x10     1.0
 3         2x10     1.0
 4         3x10     1.0
 5         3x10     9.0,
   Prescription  Weight
 0         None     1.0
 1        

In [813]:
pres_weight=[i.fillna('1x') for i in pres_weight]

In [815]:
pres_weight[0]['Prescription']

0          10
1          2x
2       2x10 
3    3x30 sec
4    2x30 sec
Name: Prescription, dtype: object

In [816]:
prescriptions=[i['Prescription'].values for i in pres_weight]

In [817]:
prescriptions

[array(['10', '2x', '2x10 ', '3x30 sec', '2x30 sec'], dtype=object),
 array(['1x', '2x', '1x', '3x30 sec', '2x30 sec'], dtype=object),
 array(['1x', '3x', '3x10', '3x10 ', '3x30 sec', '3x30 sec'], dtype=object),
 array(['1x', '3x', '3x10', '3x10 ', '3x30 sec', '3x30 sec'], dtype=object),
 array(['3x', '3x10', '3x10 ', '3x30 sec', '3x30 sec'], dtype=object),
 array(['1x', '2x', '2x10', '2x10', '3x10', '3x10'], dtype=object),
 array(['1x', '2x', '3x10 ES', '3x10 ', '3x30 sec'], dtype=object),
 array(['1x', '2x', '2x10', '2x10', '3x10', '3x10'], dtype=object),
 array(['1x', '2x', '3x10', '3x10 ', '3x30 sec', '3x30 sec'], dtype=object),
 array(['1x', '2x', '2x10', '2x10', '3x10', '3x10'], dtype=object),
 array(['1x', '2x', '3x10', '3x10 ', '3x30 sec', '3x30 sec'], dtype=object),
 array(['1x', '2x', '3x10', '3x10 ', '3x30 sec', '3x30 sec'], dtype=object),
 array(['1x', '2x', '3x10', '3x10 ', '3x30 sec', '3x30 sec'], dtype=object),
 array(['1x', '2x', '2x10', '2x10', '3x10', '3x10'], dtype=o

In [818]:
pattern = r'^(\d+)x(\d+)?(?:\s*sec|\s*\(\s*\w*\s*\)|\s*min|\s*@|)?'
outputs = []
for arr in prescriptions:
    parts_full = []
    for s in arr:
        try:
            parts = re.findall(pattern, s)
            parts_full.append(parts)
        except:
            pass
    outputs.append(parts_full)

In [819]:
outputs_fixed = [item for item in outputs if item != [[]]]

In [820]:
len(outputs_fixed)

62

In [826]:
test=outputs_fixed[0]

In [841]:
if any(not sub for sub in test):
    test = [[('1', '')] if not sub else sub for sub in test]

In [842]:
test

[[('1', '')], [('2', '')], [('2', '10')], [('3', '30')], [('2', '30')]]

In [844]:
for idx,i in enumerate(outputs_fixed):
    if any(not sub for sub in i):
        outputs_fixed[idx] = [[('1', '')] if not sub else sub for sub in i]

In [845]:
fixed_outputs=[np.array(i).reshape(-1,2) for i in outputs_fixed]

In [847]:
np.array(outputs_fixed[3]).shape

(6, 1, 2)

In [734]:
arrays[0].shape

(4, 2)

In [848]:
arrays=[np.where(i=='','1',i).astype(dtype='int') for i in fixed_outputs]

In [849]:
arrays

[array([[ 1,  1],
        [ 2,  1],
        [ 2, 10],
        [ 3, 30],
        [ 2, 30]]),
 array([[ 1,  1],
        [ 2,  1],
        [ 1,  1],
        [ 3, 30],
        [ 2, 30]]),
 array([[ 1,  1],
        [ 3,  1],
        [ 3, 10],
        [ 3, 10],
        [ 3, 30],
        [ 3, 30]]),
 array([[ 1,  1],
        [ 3,  1],
        [ 3, 10],
        [ 3, 10],
        [ 3, 30],
        [ 3, 30]]),
 array([[ 3,  1],
        [ 3, 10],
        [ 3, 10],
        [ 3, 30],
        [ 3, 30]]),
 array([[ 1,  1],
        [ 2,  1],
        [ 2, 10],
        [ 2, 10],
        [ 3, 10],
        [ 3, 10]]),
 array([[ 1,  1],
        [ 2,  1],
        [ 3, 10],
        [ 3, 10],
        [ 3, 30]]),
 array([[ 1,  1],
        [ 2,  1],
        [ 2, 10],
        [ 2, 10],
        [ 3, 10],
        [ 3, 10]]),
 array([[ 1,  1],
        [ 2,  1],
        [ 3, 10],
        [ 3, 10],
        [ 3, 30],
        [ 3, 30]]),
 array([[ 1,  1],
        [ 2,  1],
        [ 2, 10],
        [ 2, 10],
        [ 

In [850]:
arrays=[i[:,0]*i[:,1] for i in arrays]

In [760]:
len(arrays)

62

In [852]:
for df,arr in zip(dfs,arrays):
    try:
        df['Volume-Load']=df['Weight']*arr
    except:
        pass

In [787]:
dfs[1]=dfs[1].drop(columns='Total')

In [784]:
test=dfs[1]

In [853]:
dfs[1]

Exercise Prescription  Weight  Volume-Load
0                     Roll Out         None     1.0          1.0
1  Lb Warm Up (leg extensions)           2x     1.0          2.0
2     Banded Bridge Abductions         None     1.0          1.0
3                       Planks     3x30 sec     1.0         90.0
4       Side Planks from knees     2x30 sec     1.0         60.0

In [854]:
for df in dfs:
    try:
        df['Total'] = pd.Series([0] * len(df))
        df.loc[len(df) - 1, 'Total'] = df['Volume-Load'].sum()
    except:
        pass

In [855]:
dfs

[                         Exercise Prescription  Weight  Volume-Load  Total
 0                        Roll Out           10     1.0          1.0      0
 1  Lb Warm Up (no arms dead bugs)           2x     1.0          2.0      0
 2               Quad Contractions        2x10      1.0         20.0      0
 3                          Planks     3x30 sec     1.0         90.0      0
 4          Side Planks from knees     2x30 sec     1.0         60.0    173,
                       Exercise Prescription  Weight  Volume-Load  Total
 0                     Roll Out         None     1.0          1.0      0
 1  Lb Warm Up (leg extensions)           2x     1.0          2.0      0
 2     Banded Bridge Abductions         None     1.0          1.0      0
 3                       Planks     3x30 sec     1.0         90.0      0
 4       Side Planks from knees     2x30 sec     1.0         60.0    154,
                       Exercise Prescription  Weight  Volume-Load  Total
 0                     Roll Out

# Try on other people

In [1049]:
def grab_all_workouts(client_name):
    file=openpyxl.load_workbook(f'/Users/jaredperez/Client Folders/{client_name}.xlsx')
    all_sheetnames = file.sheetnames
    valid_sheetnames = [name for name in all_sheetnames if "skip" not in name]
    sheets=[file[i] for i in valid_sheetnames]
    exercises=[]
    start_row = 0

    for block in sheets:
        for row in block.iter_rows(max_col=3):
            values = []
            for cell in row:
                values.append(cell.value)
                if "workout" in str(cell.value).lower():
                    start_row = cell.row
                if start_row > 0 and cell.row >= start_row and cell.row <= start_row + 12:
                    if len(values) == 3:
                        exercises.append((values[0], values[1], values[2]))
                
    workouts = []
    current_workout = []

    start = 0
    for idx, row in enumerate(exercises):
        if row[0] is None:
            continue
        if "workout" in str(row[0]).lower():
            if current_workout:
                workouts.append(current_workout)
            current_workout = []
            start = idx
        current_workout.append(row)
    stop = idx

    if current_workout:
        workouts.append(current_workout)
        
    dfs = [pd.DataFrame(i[1:], columns=['Exercise', 'Prescription', 'Weight']) for i in workouts]
    for df in dfs:
        df['Weight'] = df['Weight'].fillna(1)
        try:
            df['Weight']=df['Weight'].astype(dtype='float64')
        except:
            pass

    
    return dfs

In [1057]:
files=grab_all_workouts('Masha')

In [1058]:
len(files)

146

In [1059]:
files[100]

Exercise Prescription  Weight
0               Banded Walks     2x60 sec     1.0
1            Up/Down & 90/90           2x     1.0
2         DB Squat Thrusters         3x10    12.0
3           DB Incline Bench         3x10    15.0
4  Alterntaing Reverse Lunge         3x10    12.0
5                  I, Y, T's         3x10     2.0
6           SL Glute Bridges         3x10     1.0
7                  Deas Bugs     3x30 sec     1.0
8             Planks Circuit           2x     1.0
9                    Stretch         None     1.0

In [1053]:
def clean_workouts(list_of_dataframes):
    for idx,df in enumerate(list_of_dataframes):
        if df['Weight'].dtype != 'float64':
            list_of_dataframes.pop(idx)
            
    for df in list_of_dataframes:
        if df['Prescription'].apply(lambda x: isinstance(x, int)).any():
            df['Prescription'] = df['Prescription'].astype(str)

    prescriptions=[i['Prescription'] for i in list_of_dataframes]
    prescriptions=[i.fillna('1x') for i in prescriptions]
    
    pattern = r'^(\d+)x(\d+)?(?:\s*sec|\s*\(\s*\w*\s*\)|\s*min|\s*@|)?'
    outputs = []
    for arr in prescriptions:
        parts_full = []
        for s in arr:
            try:
                parts = re.findall(pattern, s)
                parts_full.append(parts)
            except:
                pass
        outputs.append(parts_full)
    
    outputs_fixed = [item for item in outputs if item != [[]]]
    for idx,i in enumerate(outputs_fixed):
        if any(not sub for sub in i):
            outputs_fixed[idx] = [[('1', '')] if not sub else sub for sub in i]
        
    sets_reps=[np.array(i).reshape(-1,2) for i in outputs_fixed]
    sets_reps=[np.where(i=='','1',i).astype(dtype='int') for i in sets_reps]
    
    volume=[i[:,0]*i[:,1] for i in sets_reps]
    
    for df,arr in zip(list_of_dataframes,volume):
        df['Volume-Load']=df['Weight']*arr
        
    for df in list_of_dataframes:
        try:
            df['Total'] = pd.Series([0] * len(df))
            df.loc[len(df) - 1, 'Total'] = df['Volume-Load'].sum()
        except:
            pass
        
    return list_of_dataframes, volume, sets_reps

In [1060]:
files, volume, sets_reps=clean_workouts(files)

In [1061]:
len(files)

142

In [1062]:
files[100]

Exercise Prescription  Weight  Volume-Load  Total
0               Banded Walks     2x60 sec     1.0        120.0      0
1            Up/Down & 90/90           2x     1.0          2.0      0
2         DB Squat Thrusters           2x    18.0         36.0      0
3           DB Incline Bench         3x10    21.0        630.0      0
4  Alterntaing Reverse Lunge         3x10    18.0        540.0      0
5                  I, Y, T's         3x10     2.5         75.0      0
6           SL Glute Bridges         3x10     1.0         30.0      0
7                  Deas Bugs     3x30 sec     1.0         90.0      0
8             Planks Circuit           2x     1.0          2.0      0
9                    Stretch         None     1.0          1.0   1526

In [1044]:
volume

[array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([48, 48, 48, 48, 48, 48, 48]),
 array([ 10,   2,  48,   4,  60,  60,  60,  60, 120]),
 array([48, 48, 48, 48, 48, 48, 48, 60]),
 array([ 10,   2,  40, 120, 120,  60,  60,   4,  48,   1]),
 array([48, 48, 48, 48, 48, 48, 90]),
 array([ 10,   2,  40,   4,  40,  40,  40,  40, 120]),
 array([48, 48, 48, 48, 48, 48, 48, 48]),
 array([ 10,   2,  40, 120, 120,  40,  40,   4,  40,   1]),
 array([48, 48, 48, 48, 48, 48, 48, 48]),
 array([ 10,   2,  40,   4,  60,  60,  60,  60, 120]),
 array([48, 48, 48, 48, 48, 48, 48, 40]),
 array([10,  2, 20, 90, 90, 30, 30,  3, 30,  1]),
 array([48, 48, 48, 48, 48, 48, 48, 48]),
 array([10,  2, 30,  3, 30, 30, 30, 30, 90]),
 array([48, 48, 48, 48, 48, 48, 48, 40]),
 array([10,  2, 30, 90, 90, 30, 30,  3, 30]),
 array([48, 48, 48, 48, 48, 48]),
 array([ 10,   2,  40,  40,  40,  40,  40, 120,  40]),
 array([48, 48, 48, 48, 48, 48, 48]),
 array([10,  2, 30, 30, 30, 30, 30, 90, 30]),
 array([48, 48

In [1045]:
sets_reps

[array([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]),
 array([[ 4, 12],
        [ 4, 12],
        [ 4, 12],
        [ 4, 12],
        [ 4, 12],
        [ 4, 12],
        [ 4, 12]]),
 array([[10,  1],
        [ 2,  1],
        [ 4, 12],
        [ 4,  1],
        [ 4, 15],
        [ 4, 15],
        [ 4, 15],
        [ 4, 15],
        [ 4, 30]]),
 array([[ 4, 12],
        [ 4, 12],
        [ 4, 12],
        [ 4, 12],
        [ 4, 12],
        [ 4, 12],
        [ 4, 12],
        [ 4, 15]]),
 array([[10,  1],
        [ 2,  1],
        [ 4, 10],
        [ 4, 30],
        [ 4, 30],
        [ 4, 15],
        [ 4, 15],
        [ 4,  1],
        [ 4, 12],
        [ 1,  1]]),
 array([[ 4, 12],
        [ 4, 12],
        [ 4, 12],
        [ 4, 12],
        [ 4, 12],
        [ 4, 12],
        [ 3, 3

In [1046]:
%store sets_reps
%store volume

Stored 'sets_reps' (list)
Stored 'volume' (list)


# Creating logic for volume load...use bins and value in total column

In [999]:
totals=[i['Total'].sum() for i in files]

In [1001]:
totals.sort()

In [1004]:
totals=pd.Series(totals)

In [1009]:
bins=pd.qcut(totals, [0,.2,.4,.6,.8,1])

In [1010]:
bins

0        (-0.001, 408.0]
1        (-0.001, 408.0]
2        (-0.001, 408.0]
3        (-0.001, 408.0]
4        (-0.001, 408.0]
             ...        
344    (5503.0, 23186.0]
345    (5503.0, 23186.0]
346    (5503.0, 23186.0]
347    (5503.0, 23186.0]
348    (5503.0, 23186.0]
Length: 349, dtype: category
Categories (5, interval[float64, right]): [(-0.001, 408.0] < (408.0, 1379.8] < (1379.8, 3658.4] < (3658.4, 5503.0] < (5503.0, 23186.0]]

In [1011]:
manual_cuts=[totals[bins==category] for category in bins.cat.categories]

In [1012]:
manual_cuts

[0       0.0
 1       0.0
 2       0.0
 3      12.0
 4      16.0
       ...  
 70    408.0
 71    408.0
 72    408.0
 73    408.0
 74    408.0
 Length: 75, dtype: float64,
 75      409.0
 76      409.0
 77      409.0
 78      416.0
 79      417.0
         ...  
 135    1259.0
 136    1308.0
 137    1344.0
 138    1362.0
 139    1369.0
 Length: 65, dtype: float64,
 140    1423.0
 141    1476.0
 142    1527.0
 143    1632.0
 144    1632.0
         ...  
 204    3494.0
 205    3504.0
 206    3524.0
 207    3570.0
 208    3600.0
 Length: 69, dtype: float64,
 209    3673.0
 210    3704.0
 211    3764.0
 212    3778.0
 213    3778.0
         ...  
 275    5473.0
 276    5474.0
 277    5503.0
 278    5503.0
 279    5503.0
 Length: 71, dtype: float64,
 280     5510.0
 281     5533.0
 282     5533.0
 283     5533.0
 284     5548.0
         ...   
 344    11019.0
 345    19966.0
 346    22898.0
 347    22898.0
 348    23186.0
 Length: 69, dtype: float64]

In [1013]:
totals

0          0.0
1          0.0
2          0.0
3         12.0
4         16.0
        ...   
344    11019.0
345    19966.0
346    22898.0
347    22898.0
348    23186.0
Length: 349, dtype: float64

In [1047]:
manual_cuts[1].max()

1369.0

In [1017]:
def intensity_classification(workouts):
    totals=[workouts['Total'].sum() for i in files]

for total in totals:
    if total<=manual_cuts[0].max():
        intensity='Light'
    if total<=manual_cuts[1].max() and total>=manual_cuts[0].max():
        intensity='Moderate-Light'
    if total<=manual_cuts[2].max() and total>=manual_cuts[1].max():
        intensity='Moderate' 
    if total<=manual_cuts[3].max() and total>=manual_cuts[2].max():
        intensity='Moderate-Heavy'
    if total<=manual_cuts[4].max() and total>=manual_cuts[3].max():
        intensity='Heavy'
        
    print(intensity)

Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Moderate-Light
Mode

# trying to assign labels to dataframes

In [1056]:
files[0]

Exercise  Prescription        Weight   Volume-Load  Total
0   Squat Thrusters  4x12 @85-90%            15           720      0
1          DB Bench  4x12 @85-90%            24          1152      0
2   SA Renegade Row  4x12 @85-90%            15           720      0
3        SL RDL Row  4x12 @85-90%            15           720      0
4    Walking Lunges  4x12 @85-90%            15           720      0
5  Curl to OH Press  4x12 @85-90%            14           672      0
6               RDL  4x12 @85-90%            35          1680      0
7           Burpees          4x10             1            40      0
8         4/18-4/24  Prescription  Reps (set 1)  Reps (set 1)      0

In [1033]:
%store files

Stored 'files' (list)
